[build-system]
requires = [
    "wheel",
    "setuptools",
]

[project]
name = "darshan_logs"
dynamic = ["version"]
requires-python = ">=3.6"

[project.urls]
source = "https://github.com/darshan-hpc/darshan-logs"
tracker = "https://github.com/darshan-hpc/darshan-logs/issues"
